name: Miri

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - nightly-2024-03-10
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        timeout-minutes: 1
        continue-on-error: true
        if: matrix.os != 'macos-latest' # Cache seems to messing up macOS build
        with:
          path:
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: miri-${{ github.job }}-${{ runner.os }}-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            miri-${{ github.job }}-${{ runner.os }}-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
            miri-${{ github.job }}-${{ runner.os }}-${{ matrix.toolchain }}-

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: 'true'
          default: 'true'
          toolchain: ${{ matrix.toolchain }}
          components: miri

      - name: Test
        run: cargo miri test
